version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: fav-db-cont
    user: postgres
    environment:
      POSTGRES_DB: "fav-db"
      POSTGRES_USER: "fav-user"
      POSTGRES_PASSWORD: "fav-pass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
      - .:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "fav-db -U fav-user -d fav-db"]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 10s
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "fav@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "pass"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    depends_on:
      - postgres