eureka:
  instance:
    hostname: eureka-server
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone:  ${EUREKA_DEFAULT_ZONE:http://eureka-server:8761/eureka}

server:
  port: ${EUREKA_PORT:8761}

spring:
  application:
    name: registry-service